### ISSUE TITLE
Is usage of Boost allowed internally in the codebase?

### ISSUE THREAD

**Issue by JoeLoser** [tenzir/vast#1352]
Is using Boost allowed in this codebase? For example, I am surprised to see usage of `caf::type_list` instead of `boost::mp11::mp_list` for example. There seem to be several hand-rolled algorithms for working on type lists there, but they will be slow to compile compared to the `boost::mp11` equivalents. I understand `caf` is a submodule of `vast`, so it may just be a matter of convenience in this particular example. The question still generally holds: can we use Boost internally in vast? If so, what do we think is an appropriate minimum version to use/assume?

**Comment by dominiklohmann** [comment]
Generally, we try to avoid introducing new dependencies unless we really need to.

For type lists specifically, I don't think it is worth to add a new dependency. CAF serves us well in this case, and looking at a build of VAST with [Clang Build Analyzer](https://github.com/aras-p/ClangBuildAnalyzer) shows that our compile time woes lie elsewhere.

> Can we use Boost internally in VAST?

Not without a good reason. Sell it to us: What are you working on that would benefit from using Boost?

> Appropriate minimum version to use/assume?

We aim to support Debian Buster (with backports), which appears to support 1.71: https://packages.debian.org/search?suite=buster-backports&searchon=names&keywords=libboost

**Comment by mavam** [comment]
Some historic background: several years ago we made a strategic decision to not allow Boost in the code base.
- This was at a time where Boost was a big monolith.
- Boost came a substantial compile-time penalty due to the ambition for supporting a wide range of compilers and standards. By focusing solely on >= C++17, we can often achieve a much leaner/faster solution.
- Using Boost means that it would open that door for developers to include all sorts of other Boost libraries. This is a problem because there are substantial quality differences in the libraries.

> There seem to be several hand-rolled algorithms for working on type lists there, but they will be slow to compile compared to the boost::mp11 equivalents.

I'd be curious to see some data on this. Is this a gut feeling or do you have empirical evidence?

Please correct me if I'm wrong, @dominiklohmann, but I recall that most of our compile-time performance "issues" stem from the size of the overload set and template instantiations. We don't have that many type lists and/or type-level computation in the code base where I could imagine that switching to a different type-list implementation would bring a sizeable build performance gain.

[rant]
I'm still amazed why the standard library doesn't ship with a reasonable type list implementation for this.
[/rant]

**Comment by dominiklohmann** [comment]
> > There seem to be several hand-rolled algorithms for working on type lists there, but they will be slow to compile compared to the boost::mp11 equivalents.
> 
> I'd be curious to see some data on this. Is this a gut feeling or do you have empirical evidence?

There exist few libraries as optimized for compile time as Boost.Mp11. Regardless, I don't think switching would improve anything with regards to overall compilation time. We include CAF's type list in almost every TU transitively, and we get a lot for free by using it, e.g., we can make use of `caf::default_sum_type_access` instead of having to provide our own specialization. Maintainability vs. compilation time is where tradeoffs sometimes must be made.

> Please correct me if I'm wrong, @dominiklohmann, but I recall that most of our compile-time performance "issues" stem from the size of the overload set and template instantiations.

Most of it lies inside CAF, and the stuff that is within libvast itself we cannot solve by using Boost.

On that note, we are improving the situation constantly: Just a year ago, compiling everything took almost 50% longer than it does now. And we're all working to improve the situation constantly, but there's only so much one can do about it—which makes me quite grateful for refactoring PRs like the recent three from @JoeLoser.

**Comment by JoeLoser** [comment]
Thanks for the discussion and context.  Without having measured using `-ftime-trace` and Clang build analyzer, I can't say where the compilation time and template instantiations are mostly coming from.  The type list example was just an observation when reading code the other day (and also [base64 in the codebase](https://github.com/tenzir/vast/blob/b31f22c556585bb76af70955be3f01e6e7548469/libvast/src/detail/base64.cpp#L14)  Helping reduce compilation times may be something I pursue in the future as I have a lot of experience with heavy template metaprogramming and minimizing compilation times in those kinds of codebases.

Given the nature of the question, it has sufficiently been answered. As such, I'm going to close this issue.

**Comment by mavam** [comment]
Interestingly, we have `./configure --show-time-report` that adds `-ftime-trace`. It's been a while since anybody used this internally, presumably because the output is quite low-level and it's not immediately clear how to bring down the compile time.

**Comment by dominiklohmann** [comment]
`--show-time-report` enables `-ftime-report`, not `-ftime-trace`, which is fundamentally different. See also https://github.com/tenzir/vast/pull/1359.
