### ISSUE TITLE
VAST AWS deployment

### ISSUE THREAD

**Issue by rdettai** [tenzir/vast#2098]
### Use Case

I want to use VAST to monitor my application that runs on the AWS Cloud. 

### Feature Description

I propose to:
- use Terraform for the deployment
- run VAST on Fargate using the [official docker images dockerhub](https://hub.docker.com/r/tenzir/vast)
- offer a VAST client running on AWS Lambda

#### Subtasks:
- [ ] https://github.com/tenzir/vast/pull/2102: terraform script that deploys VAST with [task storage](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html) only 
- [ ] #2108: creates an easy way to interact with the VAST server on fargate

**Comment by mavam** [comment]
> * use Terraform for the deployment

Agreed. This makes it also easy to migrate the AWS setup to other clouds later.

> * run VAST on Fargate using the [official docker images dockerhub](https://hub.docker.com/r/tenzir/vast)

Perfect to get started on AWS with with as little friction as possible.

> * offer the choice between multiple types of persistent storage for VAST (EBS, EFS...)

While choice would be nice, let's first analyze what gets us fastest to an end-to-end MVP. I yet have to take a deeper look at EBF, EFS, and S3.  

> * include Terraform scripts for Zeek and Suricata

This would be great to ship in order to let users spin up an environment in their tenant. There are a lot of moving parts to consider, e.g., virtual taps, running from traces, etc., that we can ship incrementally. For example, we already have a [dockerized Zeek](https://github.com/tenzir/dockerized-zeek) that makes it easy to provide a PCAP file that Zeek then turns into logs. That's far easier than dealing with VPC tapping. Once we got that up and running, we'll look into the VPC tapping.

Same with Suricata. I'm going to check with @satta regarding choice of Suricata Docker images that support deterministic, PCAP-driven generation of EVE logs.
   
>   * have a customizable number of mirrored network interfaces for each
>   * if at least one mirroring is defined for a given IDS, spin up an instance for it

I like this UX, but the VPC mirroring strategy is also highly customer dependent. Once we have the initial small-scale deterministic environment in place, we may want to reach out to some users.

**Comment by rdettai** [comment]
Thanks for the feedback @mavam !

I have re-organized the tasks into a set of "MVP" features and longer term objectives.

I think I will also provide access to the long running VAST server through VAST client instances running on lambda for ad-hoc imports and queries. The cold start will be huge because the VAST docker image is large, but it will allow a flexible access to VAST using the AWS control pane (using the AWS IAM for access control).

**Comment by rdettai** [comment]
I am re-focusing this issue on the deployment of VAST itself. Loading data from a dataset and deploying an IDS will be managed in subsequent issues.
