### ISSUE TITLE
Contextual expression

### ISSUE THREAD

**Issue by geekscrapy** [tenzir/vast#2793]
### Use Case

This would allow an analyst the ability to see the build-up to an event without crafting multiple searches. This is good for things like analysing web log activity and zeek events where you may have an alert for one IP, but there are other IPs exhibiting the same behaviour (but you miss because the alert focuses on one IP).

### Feature Description

It would be great if there was the ability to apply a search, but for each search result expand the output by a certain number of lines/logs/packets etc. by a set amount to provide additional context. This is much like the grep features -C, -A and -B.

Ideally, the expansion could take a couple of forms:
1. A number (like grep) of log lines either side of the even
2. A number of seconds either side of the event

**Comment by dominiklohmann** [comment]
Welcome to VAST! 👋

This is a great feature request, and it is partially covered by an experimental feature VAST already has, which I would like to explain, and then I also want to go a bit deeper on how we want to stabilize that feature in the near future.

> A number of seconds either side of the event

VAST already supports this, at least for the `-A` and `-B` flags. This feature is in an experimental command named `explore`, which has a slightly different syntax from the `export` command.

```
vast explore [options] <query-expression>
```


Where `[options]` can be any of the following:

- `[--format=<format>]` defaults to `json`, similar to the export format that for `export` has to be passed as a positional argument.
- `[-A <duration>]` or `[--after=<duration>]` include all events in the result whose event timestamp is within any of the initial query result's timestamp plus the given duration. For example, `-A 5s`. Note that the argument takes a unit.
- `[-B <duration>]` or `[--before=<duration>]` similar to `-A`, except that we're subtracting rather than adding the duration.
- `[--by=<field>]` restricts the explored events from `-A` and `-B` by requiring them to match their respective initial event's value in the specified field.
- `[-n <num-events>]` or `[--max-events=<num-events>]` restricts the number of results in total.
- `[--max-events-query=<num-events>]` restricts the number of results for the initial query.
- `[--max-events-context=<num-events>]` restricts the number of results fetched as context per result in the initial query.

There is no `-C <duration>` currently, but you can achieve this by just setting `-A` and `-B` explicitly.

Note that the `explore` command can be really expensive if the number of initial events is high, so I would generally recommend limiting that.

In the near- to medium-term future we're looking to add pipelines to the `export` command (see [RFC-001](https://github.com/tenzir/vast/blob/master/rfc/001-composable-pipelines/README.md) and #2600), allowing the user to write something like `vast export <format> '<query-expression> | explore -A 1s -B 1s'`. We plan to finish a first version of this sometime in January, porting the [existing operators](https://vast.io/docs/understand/query-language/operators) first and then adding additional ones. High up on our internal wishlist are `pivot` and `explore` to supersede the currently experimental commands and to stabilize them.

> A number (like grep) of log lines either side of the event

This is hard to model with VAST, which for input sources that have no single shape cannot keep this context around easily.

The ordering guarantee VAST currently has is that events of the same schema and from the same data source are ordered—but as soon as multiple schemas or multiple data sources with overlapping schemas come into play this breaks.

For this I would like to understand your use case better, because there are some things we can do, but the solution it's not as straightforward as it is for `grep`. Could you explain when you would use this over the temporal context?

Please note that we're always happy to chat to find out what we can do to make VAST work better for your use cases. There's our community Slack at [slack.tenzir.com](https://slack.tenzir.com) and you can also always [schedule a call with me](https://calendly.com/dominiklohmann/30min).
